const DEFAULT_CONFIG={name:'Sportzfy TV',version:'1.0.0',tagline:'Worldwide sports streaming for Android & TV',description:'A fast, modern sports streaming companion built for Android phones, tablets and TV screens.',logo:'assets/logo.png',mainDownload:'#',mirrors:[],screenshots:[{src:'assets/d576f892-41d6-43cd-b3cd-f93b9adc404c-screen.png',label:'Live events home'},{src:'assets/e8dc4806-6da2-4c5c-9c59-3909c50868c4-screen.png',label:'Categories'},{src:'assets/a3313e29-0b85-46a4-98ac-3b4b4707f714-screen.png',label:'Sports categories'},{src:'assets/8a48a50c-8000-47e8-8216-bdcb5e8bd99f-screen.png',label:'Channel browser'}]};
let config=DEFAULT_CONFIG, shots=[], shotIndex=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function loadConfig(){try{const r=await fetch(new URL('config.json',document.baseURI),{cache:'no-store'});if(r.ok)config={...DEFAULT_CONFIG,...await r.json()}}catch(e){}const local=localStorage.getItem('sportzfy-tv-config');if(local){try{config={...config,...JSON.parse(local)}}catch(e){}}applyConfig()}
function applyConfig(){ $$('[data-config-name]').forEach(x=>x.textContent=config.name);$$('[data-config-version]').forEach(x=>x.textContent=config.version);$$('[data-config-description]').forEach(x=>x.textContent=config.description||config.tagline);$('#brandLogo').src=config.logo||DEFAULT_CONFIG.logo;$('#heroDownload').href=config.mainDownload||'#';$('#mainDownload').href=config.mainDownload||'#';const mirrors=$('#mirrors');mirrors.innerHTML='';(config.mirrors||[]).filter(m=>m.url).forEach(m=>{const a=document.createElement('a');a.className='mirror';a.href=m.url;a.target='_blank';a.rel='noopener';a.textContent=m.name||'Mirror';mirrors.appendChild(a)});shots=(config.screenshots&&config.screenshots.length?config.screenshots:DEFAULT_CONFIG.screenshots);renderShot(0)}
function renderShot(i){shotIndex=(i+shots.length)%shots.length;const s=shots[shotIndex];$('#galleryScreen').src=s.src;$('#heroScreen').src=s.src;$('#screenLabel').textContent=s.label||`Screenshot ${shotIndex+1}`;const dots=$('#shotDots');dots.innerHTML=shots.map((_,n)=>`<span class="dot ${n===shotIndex?'active':''}"></span>`).join('')}
$('#prevShot').addEventListener('click',()=>renderShot(shotIndex-1));$('#nextShot').addEventListener('click',()=>renderShot(shotIndex+1));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
const canvas=$('#stars'),ctx=canvas.getContext('2d');let stars=[];function resizeStars(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(180,Math.floor(innerWidth/7))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.2,a:Math.random()*.65+.15,s:Math.random()*.3+.05}))}function starLoop(){ctx.clearRect(0,0,innerWidth,innerHeight);stars.forEach(s=>{s.y-=s.s;if(s.y<0)s.y=innerHeight;ctx.globalAlpha=s.a*(.65+.35*Math.sin(Date.now()/800+s.x));ctx.fillStyle='#bcefff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(starLoop)}addEventListener('resize',resizeStars);resizeStars();starLoop();$('#year').textContent=new Date().getFullYear();loadConfig();
